gigaspaces:
  version: 17.1.2
  home: /home/dixson/gigaspaces-smart-cache-enterprise-17.1.2

docker:
  username: dixsonhuie1

spring:
  framework:
    version: 6.2.1
  boot:
    version: 3.4.7

springdoc:
  version: 2.7.0

app:
  version: 1.0-SNAPSHOT
  docker:
    version: latest

