gigaspaces:
  version: 17.1.2
  home: /Users/aharonmoll/Documents/GigaSpaces/gigaspaces-smart-cache-enterprise-17.1.2

docker:
  username: aharon172

spring:
  framework:
    version: 5.3.29
  boot:
    version: 2.7.9

springfox:
  version: 3.0.0

app:
  version: 1.0-SNAPSHOT
  docker:
    version: latest

